
class ExampleService {
    public async loadCountries(): Promise<any> {
        return countries;
    }
    public async loadStates(): Promise<any> {
        return states;
    }
    public async loadCustomers(): Promise<any> {
        return customers;
    }
    public async loadMemberLevels(): Promise<any> {
        return memberLevels;
    }
    public async loadCustomerData(): Promise<any> {
        return customer.data;
    }
    public async loadRoles(): Promise<any> {
        return roles;
    }
    public async loadProduct(): Promise<any> {
        return product.data;
    }
}

export const exampleService: ExampleService = new ExampleService();

const countries: any = [
    {
        name: "Argentina",
        id: "AR",
    },
    {
        name: "Venezuela",
        id: "VEN",
    },
];

const states: any = [
    {
        name: "Caracas",
        id: 1,
    },
    {
        name: "Buenos aires",
        id: 2,
    },
];

const roles: any = [
    {
        name: "Role 1",
        id: 1,
    },
    {
        name: "Role 1",
        id: 2,
    },
];

const customers: any = [
    {
        name: "Luis Acevedo",
        id: 1,
    },
    {
        name: "Luis Daniel",
        id: 2,
    },
    {
        name: "Emelson",
        id: 3,
    },
];

const memberLevels: any = [
    {
        name: "Gold",
        id: 1,
    },
    {
        name: "Silver",
        id: 2,
    },
];

const customer: any = {
    code: 200,
    status: "success",
    data: {
        id: 3,
        first_name: "Lillian",
        middle_name: "Manley",
        last_name: "Brekke",
        phone: "693.952.6180",
        cellphone: "279.783.7243 x1529",
        birthday: "1991-05-08",
        address: "45309 Conner Pines\nAlbertoport, NY 46912-4507",
        apt_suite: "13X",
        city: "Marvinview",
        state: "Oregon",
        country: "Togo",
        zip: "71799",
        email: "idell42@gmail.com",
        gender: null,
        id_number: "7580195",
        id_type: "ID",
        id_expiration: "2019-08-06",
        id_is_temporary: false,
        member_level_id: 1,
        flat_discount_rate: 10,
        avatar_file_name: "example_person_4.png",
        avatar_file_size: 638885,
        avatar_content_type: "image/png",
        avatar_variants: [],
        avatar_updated_at: "2019-07-22 21:16:31",
        type: "REGISTERED",
        status: "ACTIVE",
        status_at: "2019-08-20T12:53:32+00:00",
        doc_name: null,
        account_id: 1,
        shows_checkin_note: true,
        referred_by_id: null,
        avatar_medium_url: "https://dev.static.dispensary.helixcore.com/customers/3/avatar/medium/example_person_4.png",
        avatar_thumb_url: "https://dev.static.dispensary.helixcore.com/customers/3/avatar/thumb/example_person_4.png",
        avatar_original_url: "https://dev.static.dispensary.helixcore.com/customers/3/avatar/original/example_person_4.png",
        notes: [
            {
                id: 39,
                notable_type: "App\\Models\\Store\\Customer",
                notable_id: 3,
                name: "customer note",
                title: "customer note title",
                note: "Nota",
                created_by: "8",
                account_id: 1,
            },
        ],
        profiles: [
            {
                id: 3,
                customer_id: 3,
                fax: "312-267-0228",
                dea: null,
                website: "http://www.orn.info/quibusdam-sunt-harum-minima-qui-veritatis-magni-rem",
                doctor_license: "3403460",
                doctor_active_license: 0,
                visits: 2,
                profile_type: "DOCTOR",
                medical_card_number: "5641305",
                medical_card_expiration: "2010-02-09",
                caregiver_id: null,
                doctor_id: null,
                doctor: null,
                caregiver: null,
                conditions: [],
            },
            {
                id: 90,
                customer_id: 3,
                fax: null,
                dea: null,
                website: null,
                doctor_license: null,
                doctor_active_license: 1,
                visits: null,
                profile_type: "PATIENT",
                medical_card_number: null,
                medical_card_expiration: null,
                caregiver_id: null,
                doctor_id: null,
                doctor: null,
                caregiver: null,
                conditions: [],
            },
            {
                id: 91,
                customer_id: 3,
                fax: null,
                dea: null,
                website: null,
                doctor_license: null,
                doctor_active_license: 1,
                visits: null,
                profile_type: "CAREGIVER",
                medical_card_number: null,
                medical_card_expiration: null,
                caregiver_id: null,
                doctor_id: null,
                doctor: null,
                caregiver: null,
                conditions: [],
            },
        ],
        attachments: [],
        serving_number: null,
        applicable_limits: [
            {
                rule_config: {
                    amount: 4,
                    rule_name: "Usable",
                    unit: "oz",
                },
                used: 0,
            },
            {
                rule_config: {
                    amount: 1,
                    rule_name: "Concentrate",
                    unit: "oz",
                },
                used: 0,
            },
            {
                rule_config: {
                    amount: 15,
                    rule_name: "Mature Plants",
                    unit: "oz",
                },
                used: 0,
            },
            {
                rule_config: {
                    amount: 17,
                    rule_name: "Usable",
                    unit: "g",
                },
                used: 0,
            },
        ],
    },
};

const product: any = {
    code: 200,
    status: "success",
    data: {
        id: 1,
        name: "Benshi - Concentrate",
        product_category_id: 2,
        strain_id: 8,
        batch_type_id: 2,
        brand_id: 3,
        vendor_id: 3,
        product_group_id: null,
        requires_weighing: 0,
        require_inventory: 1,
        member_discount: 0,
        member_only: 0,
        marijuana: 0,
        pre_packaged: 0,
        usable_weight: 2,
        unit: "g",
        barcode: "12121212",
        lasting_effect_unit: null,
        lasting_effect_timeframe: null,
        image_file_name: "100-Dollar-Bill-(Green).png",
        image_file_size: 4191,
        image_content_type: "image\/png",
        image_variants: "[]",
        image_updated_at: "2019-08-22T22:29:25+00:00",
        account_id: 1,
        created_by: 3,
        updated_by: 3,
        deleted_by: null,
        deleted_at: null,
        created_at: "2019-07-22T21:16:50+00:00",
        updated_at: "2019-09-02T19:05:51+00:00",
        parent_id: 1,
        location_id: 1,
        image_medium_url: "https:\/\/dev.static.dispensary.helixcore.com\/products\/1\/image\/medium\/100-Dollar-Bill-(Green).png",
        image_thumb_url: "https:\/\/dev.static.dispensary.helixcore.com\/products\/1\/image\/thumb\/100-Dollar-Bill-(Green).png",
        image_original_url: "https:\/\/dev.static.dispensary.helixcore.com\/products\/1\/image\/original\/100-Dollar-Bill-(Green).png",
        is_complete: true,
        cost: {
            current_total_cost: 110923.95999999999,
            average_cost_per_unit: 35.50857142857143,
            total_potential_profit: 54759.44,
        },
        type: {
            id: 2,
            name: "Concentrate",
            sales_limit_exempt: 0,
            account_id: 1,
            deleted_at: null,
            created_at: "2019-07-22T21:16:50+00:00",
            updated_at: "2019-09-02T15:14:53+00:00",
            batch_type_state_reporting_id: 6,
            parent_id: 2,
            location_id: 1,
        },
        category: {
            id: 2,
            name: "Concentrates",
            shared: 1,
            account_id: 1,
            deleted_at: null,
            created_at: "2019-07-22T21:16:49+00:00",
            updated_at: "2019-08-22T22:29:26+00:00",
            parent_id: 2,
            location_id: 1,
        },
        packaging_detail: {
            id: 224,
            ingredients: "Test",
            allergens: "Test",
            manufacturer_id: 6,
            cultivator_id: 7,
            activation_time: 1,
            activation_time_unit: "H",
            lasting_effect_time: 1,
            lasting_effect_time_unit: "H",
            suggested_amount: 1,
            serving_size: 1,
            serving_size_unit: "ounce",
            serving_size_of_the_container: 1,
            product_id: 1,
            recreational_template_label_id: 1,
            medical_template_label_id: 1,
            inventory_template_label_id: 1,
            created_by: "14",
            updated_by: "3",
            deleted_at: null,
            created_at: "2019-08-22T22:29:25+00:00",
            updated_at: "2019-09-02T19:06:19+00:00",
            parent_id: 224,
            location_id: 1,
            account_id: 1,
            cultivator: {
                id: 7,
                name: "Katheryn Torphy 5783",
                address1: "2500 Adriana Fords\nNew Macimouth, NY 05892-5108",
                address2: "75197 Estevan Ridges\nCortneymouth, KS 46326-7459",
                city: "North Aureliaport",
                state: "Cyprus",
                country: "Serbia",
                zip: "62722",
                phone1: "(524) 808-4186 x0153",
                website: "http:\/\/www.doyle.info\/dolore-enim-sapiente-impedit-et-repellendus-iure-dolor",
                license: "z",
                type: "MANUFACTURER",
                account_id: 1,
                created_by: "3",
                updated_by: "14",
                deleted_by: null,
                deleted_at: null,
                created_at: "2019-07-22T21:16:28+00:00",
                updated_at: "2019-08-28T14:54:05+00:00",
                parent_id: 7,
                location_id: 1,
            },
            manufacturer: {
                id: 6,
                name: "Jasmin Conn 7966",
                address1: "4888 Theodora Trail Apt. 466\nPort Kellie, VT 27331",
                address2: "39020 Spinka Run Apt. 442\nNorth Luigichester, MD 95251-9057",
                city: "Joanaport",
                state: "France",
                country: "Sweden",
                zip: "98135-4726",
                phone1: "459.253.1672",
                website: "http:\/\/trantow.com\/distinctio-possimus-nisi-voluptates-culpa-voluptates",
                license: "u",
                type: "MANUFACTURER",
                account_id: 1,
                created_by: "3",
                updated_by: "17",
                deleted_by: null,
                deleted_at: null,
                created_at: "2019-07-22T21:16:28+00:00",
                updated_at: "2019-08-30T13:36:33+00:00",
                parent_id: 6,
                location_id: 1,
            },
        },
        prices: [
            {
                id: 3562,
                entity_id: 1,
                entity_type: "App\\Models\\Inventory\\Product",
                quantity: 1,
                pre_excise: 8.130081300813009,
                price: 7.390983000739098,
                post_tax: 11,
                type: "RETAIL_RECREATIONAL",
                tax_category_id: 1,
                member_level_id: null,
                location_id: 1,
                account_id: 1,
                created_by: "16",
                updated_by: "14",
                deleted_at: null,
                created_at: "2019-08-14T20:17:08+00:00",
                updated_at: "2019-08-22T22:29:26+00:00",
                parent_id: 3562,
                tax_category: {
                    id: 1,
                    name: "Standard",
                    location_id: 1,
                    account_id: 1,
                    deleted_at: null,
                    created_at: "2019-07-22T21:16:28+00:00",
                    updated_at: "2019-07-22T21:16:28+00:00",
                    is_default: 0,
                    overall_rate: "10% + 23% + 10% + $20",
                    taxes: [
                        {
                            id: 1,
                            name: "Basic product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_PRE_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 2,
                            name: "New product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_POST_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 3,
                            name: "Medium product",
                            rate: 15,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 4,
                            name: "Premium product",
                            rate: 20,
                            tax_category_id: 1,
                            type: "PER_TRANSACTION",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 5,
                            name: "Medium product",
                            rate: 8,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                    ],
                },
            },
            {
                id: 3563,
                entity_id: 1,
                entity_type: "App\\Models\\Inventory\\Product",
                quantity: 3,
                pre_excise: 11.086474501108647,
                price: 10.078613182826041,
                post_tax: 15,
                type: "RETAIL_RECREATIONAL",
                tax_category_id: 1,
                member_level_id: null,
                location_id: 1,
                account_id: 1,
                created_by: "16",
                updated_by: "14",
                deleted_at: null,
                created_at: "2019-08-14T20:17:08+00:00",
                updated_at: "2019-08-22T22:29:26+00:00",
                parent_id: 3563,
                tax_category: {
                    id: 1,
                    name: "Standard",
                    location_id: 1,
                    account_id: 1,
                    deleted_at: null,
                    created_at: "2019-07-22T21:16:28+00:00",
                    updated_at: "2019-07-22T21:16:28+00:00",
                    is_default: 0,
                    overall_rate: "10% + 23% + 10% + $20",
                    taxes: [
                        {
                            id: 1,
                            name: "Basic product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_PRE_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 2,
                            name: "New product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_POST_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 3,
                            name: "Medium product",
                            rate: 15,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 4,
                            name: "Premium product",
                            rate: 20,
                            tax_category_id: 1,
                            type: "PER_TRANSACTION",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 5,
                            name: "Medium product",
                            rate: 8,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                    ],
                },
            },
            {
                id: 3564,
                entity_id: 1,
                entity_type: "App\\Models\\Inventory\\Product",
                quantity: 5,
                pre_excise: 14.781966001478196,
                price: 13.438150910434722,
                post_tax: 20,
                type: "RETAIL_RECREATIONAL",
                tax_category_id: 1,
                member_level_id: null,
                location_id: 1,
                account_id: 1,
                created_by: "16",
                updated_by: "14",
                deleted_at: null,
                created_at: "2019-08-14T20:17:08+00:00",
                updated_at: "2019-08-22T22:29:26+00:00",
                parent_id: 3564,
                tax_category: {
                    id: 1,
                    name: "Standard",
                    location_id: 1,
                    account_id: 1,
                    deleted_at: null,
                    created_at: "2019-07-22T21:16:28+00:00",
                    updated_at: "2019-07-22T21:16:28+00:00",
                    is_default: 0,
                    overall_rate: "10% + 23% + 10% + $20",
                    taxes: [
                        {
                            id: 1,
                            name: "Basic product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_PRE_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 2,
                            name: "New product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_POST_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 3,
                            name: "Medium product",
                            rate: 15,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 4,
                            name: "Premium product",
                            rate: 20,
                            tax_category_id: 1,
                            type: "PER_TRANSACTION",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 5,
                            name: "Medium product",
                            rate: 8,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                    ],
                },
            },
            {
                id: 3565,
                entity_id: 1,
                entity_type: "App\\Models\\Inventory\\Product",
                quantity: 2,
                pre_excise: 10.942760942760941,
                price: 9.947964493419036,
                post_tax: 13,
                type: "RETAIL_MEDICAL",
                tax_category_id: 1,
                member_level_id: 2,
                location_id: 1,
                account_id: 1,
                created_by: "16",
                updated_by: "14",
                deleted_at: null,
                created_at: "2019-08-14T20:17:08+00:00",
                updated_at: "2019-08-22T22:29:26+00:00",
                parent_id: 3565,
                tax_category: {
                    id: 1,
                    name: "Standard",
                    location_id: 1,
                    account_id: 1,
                    deleted_at: null,
                    created_at: "2019-07-22T21:16:28+00:00",
                    updated_at: "2019-07-22T21:16:28+00:00",
                    is_default: 0,
                    overall_rate: "10% + 23% + 10% + $20",
                    taxes: [
                        {
                            id: 1,
                            name: "Basic product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_PRE_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 2,
                            name: "New product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_POST_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 3,
                            name: "Medium product",
                            rate: 15,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 4,
                            name: "Premium product",
                            rate: 20,
                            tax_category_id: 1,
                            type: "PER_TRANSACTION",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 5,
                            name: "Medium product",
                            rate: 8,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                    ],
                },
            },
            {
                id: 3566,
                entity_id: 1,
                entity_type: "App\\Models\\Inventory\\Product",
                quantity: 4,
                pre_excise: 13.468013468013467,
                price: 12.24364860728497,
                post_tax: 16,
                type: "RETAIL_MEDICAL",
                tax_category_id: 1,
                member_level_id: 2,
                location_id: 1,
                account_id: 1,
                created_by: "16",
                updated_by: "14",
                deleted_at: null,
                created_at: "2019-08-14T20:17:08+00:00",
                updated_at: "2019-08-22T22:29:26+00:00",
                parent_id: 3566,
                tax_category: {
                    id: 1,
                    name: "Standard",
                    location_id: 1,
                    account_id: 1,
                    deleted_at: null,
                    created_at: "2019-07-22T21:16:28+00:00",
                    updated_at: "2019-07-22T21:16:28+00:00",
                    is_default: 0,
                    overall_rate: "10% + 23% + 10% + $20",
                    taxes: [
                        {
                            id: 1,
                            name: "Basic product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_PRE_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 2,
                            name: "New product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_POST_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 3,
                            name: "Medium product",
                            rate: 15,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 4,
                            name: "Premium product",
                            rate: 20,
                            tax_category_id: 1,
                            type: "PER_TRANSACTION",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 5,
                            name: "Medium product",
                            rate: 8,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                    ],
                },
            },
            {
                id: 3567,
                entity_id: 1,
                entity_type: "App\\Models\\Inventory\\Product",
                quantity: 10,
                pre_excise: 84.17508417508417,
                price: 76.52280379553105,
                post_tax: 100,
                type: "WHOLESALE_INBOUND",
                tax_category_id: 1,
                member_level_id: null,
                location_id: 1,
                account_id: 1,
                created_by: "16",
                updated_by: "14",
                deleted_at: null,
                created_at: "2019-08-14T20:17:08+00:00",
                updated_at: "2019-08-22T22:29:26+00:00",
                parent_id: 3567,
                tax_category: {
                    id: 1,
                    name: "Standard",
                    location_id: 1,
                    account_id: 1,
                    deleted_at: null,
                    created_at: "2019-07-22T21:16:28+00:00",
                    updated_at: "2019-07-22T21:16:28+00:00",
                    is_default: 0,
                    overall_rate: "10% + 23% + 10% + $20",
                    taxes: [
                        {
                            id: 1,
                            name: "Basic product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_PRE_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 2,
                            name: "New product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_POST_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 3,
                            name: "Medium product",
                            rate: 15,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 4,
                            name: "Premium product",
                            rate: 20,
                            tax_category_id: 1,
                            type: "PER_TRANSACTION",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 5,
                            name: "Medium product",
                            rate: 8,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                    ],
                },
            },
            {
                id: 3568,
                entity_id: 1,
                entity_type: "App\\Models\\Inventory\\Product",
                quantity: 20,
                pre_excise: 200,
                price: 200,
                post_tax: 200,
                type: "WHOLESALE_OUTBOUND",
                tax_category_id: 2,
                member_level_id: null,
                location_id: 1,
                account_id: 1,
                created_by: "16",
                updated_by: "14",
                deleted_at: null,
                created_at: "2019-08-14T20:17:08+00:00",
                updated_at: "2019-08-22T22:29:26+00:00",
                parent_id: 3568,
                tax_category: {
                    id: 2,
                    name: "Exempt",
                    location_id: 1,
                    account_id: 1,
                    deleted_at: null,
                    created_at: "2019-07-22T21:16:28+00:00",
                    updated_at: "2019-07-22T21:16:28+00:00",
                    is_default: 0,
                    overall_rate: "",
                    taxes: [

                    ],
                },
            },
            {
                id: 3776,
                entity_id: 1,
                entity_type: "App\\Models\\Inventory\\Product",
                quantity: 12,
                pre_excise: 8.869179600886918,
                price: 8.062890546260833,
                post_tax: 12,
                type: "RETAIL_MEDICAL",
                tax_category_id: 1,
                member_level_id: null,
                location_id: 1,
                account_id: 1,
                created_by: "8",
                updated_by: "8",
                deleted_at: null,
                created_at: "2019-08-26T17:40:47+00:00",
                updated_at: "2019-08-26T17:40:49+00:00",
                parent_id: 3776,
                tax_category: {
                    id: 1,
                    name: "Standard",
                    location_id: 1,
                    account_id: 1,
                    deleted_at: null,
                    created_at: "2019-07-22T21:16:28+00:00",
                    updated_at: "2019-07-22T21:16:28+00:00",
                    is_default: 0,
                    overall_rate: "10% + 23% + 10% + $20",
                    taxes: [
                        {
                            id: 1,
                            name: "Basic product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_PRE_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 2,
                            name: "New product",
                            rate: 10,
                            tax_category_id: 1,
                            type: "EXCISE_POST_TAX",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 3,
                            name: "Medium product",
                            rate: 15,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 4,
                            name: "Premium product",
                            rate: 20,
                            tax_category_id: 1,
                            type: "PER_TRANSACTION",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                        {
                            id: 5,
                            name: "Medium product",
                            rate: 8,
                            tax_category_id: 1,
                            type: "NORMAL",
                            deleted_at: null,
                            account_id: 1,
                            created_at: "2019-07-22T21:16:28+00:00",
                            updated_at: "2019-07-22T21:16:28+00:00",
                        },
                    ],
                },
            },
        ],
        price_settings: {
            id: 1,
            default_cost_per_unit: 88,
            price_point_by_usable_weight: 0,
            block_item_from_being_sold_below_cost_per_unit: 1,
            member_discount_eligible: 1,
            block_item_from_being_sold_at_zero_cost: 1,
            members_only_product: 1,
            product_id: 1,
            location_id: 1,
            account_id: 1,
            created_by: "3",
            updated_by: "3",
            deleted_at: null,
            created_at: "2019-07-22T21:16:50+00:00",
            updated_at: "2019-09-02T19:05:51+00:00",
            parent_id: 1,
        },
    },
};
